"""Initial db

Revision ID: 05468d0fb73e
Revises: 
Create Date: 2022-11-22 11:44:29.243093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05468d0fb73e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
