"""

Revision ID: 10161e3c962f
Revises: 3e38965612f3
Create Date: 2022-12-12 10:53:49.679090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10161e3c962f'
down_revision = '3e38965612f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('points_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpoints_id'), 'userpoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpoints_id'), table_name='userpoints')
    op.drop_table('userpoints')
    # ### end Alembic commands ###
