"""

Revision ID: 3e38965612f3
Revises: 1f26e6b0aa4b
Create Date: 2022-12-09 10:24:01.372423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e38965612f3'
down_revision = '1f26e6b0aa4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('round', sa.Integer(), nullable=False))
    op.add_column('points', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint('points_user_id_fkey', 'points', type_='foreignkey')
    op.create_foreign_key(None, 'points', 'player', ['player_id'], ['id'])
    op.drop_column('points', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.create_foreign_key('points_user_id_fkey', 'points', 'user', ['user_id'], ['id'])
    op.drop_column('points', 'player_id')
    op.drop_column('match', 'round')
    # ### end Alembic commands ###
