"""Initial db

Revision ID: 43f25444a4c1
Revises: 05468d0fb73e
Create Date: 2022-11-22 11:53:57.690779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f25444a4c1'
down_revision = '05468d0fb73e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
