"""added match and points tables

Revision ID: 641d0492e77f
Revises: 0e83cdc0d7c6
Create Date: 2022-12-02 11:08:06.945996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641d0492e77f'
down_revision = '0e83cdc0d7c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
