"""

Revision ID: 7d46f31bb0c4
Revises: 57ac772ee64f
Create Date: 2022-12-07 14:27:15.023555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d46f31bb0c4'
down_revision = '02185f620e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineuplimits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gk', sa.Integer(), nullable=False),
    sa.Column('df', sa.Integer(), nullable=False),
    sa.Column('mf', sa.Integer(), nullable=False),
    sa.Column('fw', sa.Integer(), nullable=False),
    sa.Column('lineup_status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineup_status')
    )
    op.create_index(op.f('ix_lineuplimits_id'), 'lineuplimits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineuplimits_id'), table_name='lineuplimits')
    op.drop_table('lineuplimits')
    # ### end Alembic commands ###
