"""

Revision ID: e2069e7ab78f
Revises: b665aefc2d03
Create Date: 2022-12-14 13:15:26.396598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2069e7ab78f'
down_revision = 'b665aefc2d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'league', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='foreignkey')
    op.drop_column('league', 'owner_id')
    # ### end Alembic commands ###
